# supported versions here: https://github.com/googlecontainertools/distroless
ARG DEBIAN_VERSION_NUMBER=13
# supported builder cpu architectures here: https://github.com/rust-cross/rust-musl-cross
ARG RUST_MUSL_CROSS_TAG=x86_64-musl

########################
## builder image
########################
FROM ghcr.io/rust-cross/rust-musl-cross:${RUST_MUSL_CROSS_TAG} AS builder

ARG COMPILE_TARGET=x86_64-unknown-linux-musl

RUN apt-get update \
    && apt-get -y install git cmake perl pkg-config libclang-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add ${COMPILE_TARGET}

WORKDIR /redlib

# display backtrace on build error
ENV RUST_BACKTRACE=full

# download (most) dependencies in their own layer
COPY Cargo.lock Cargo.toml ./
RUN mkdir src && echo "fn main() { panic!(\"why am i running?\") }" > src/main.rs
RUN cargo build --release --locked --bin redlib --target ${COMPILE_TARGET}
RUN rm ./src/main.rs && rmdir ./src

# copy the source and build the redlib binary
COPY . ./
RUN cargo build --release --locked --bin redlib --target ${COMPILE_TARGET}
RUN echo "finished building redlib!"

########################
## release image
########################
FROM gcr.io/distroless/static-debian${DEBIAN_VERSION_NUMBER}:nonroot AS release

ARG COMPILE_TARGET=x86_64-unknown-linux-musl

# Import redlib binary from builder
COPY --from=builder --chown=65532:65532 /redlib/target/${COMPILE_TARGET}/release/redlib /usr/local/bin/redlib

# Document that we intend to expose port 8080 to whoever runs the container
EXPOSE 8080

# Run a healthcheck every minute to make sure redlib is functional
HEALTHCHECK --interval=1m --timeout=3s CMD wget --spider -q http://localhost:8080/settings || exit 1

# Add container metadata
LABEL org.opencontainers.image.authors="sigaloid"

CMD ["redlib"]
