name: Build Artifact

on:
  push:
    paths-ignore:
      - "*.md"
      - "compose.*"
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      skip-debug-build:
        type: boolean
        default: false
  workflow_call:
    inputs:
      skip-debug-build:
        type: boolean
        default: false

env: 
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always

  CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"
  CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare Build
    runs-on: ubuntu-slim
    permissions: {}
    outputs:
      build_profiles: ${{ steps.set-build-profile-matrix.outputs.BUILD_PROFILES }}
    steps:
      - id: set-build-profile-matrix
        run: |
          BUILD_PROFILES="[]"
          BUILD_PROFILES=$(jq -c '. + ["release"]' <<< "$BUILD_PROFILES")
          if [[ "${{ inputs.skip-debug-build }}" == "false" ]]; then
            BUILD_PROFILES=$(jq -c '. + ["debug"]' <<< "$BUILD_PROFILES")
          fi
          jq 'if length == 0 then error("array is empty") else . end' <<< "$BUILD_PROFILES"
          echo "BUILD_PROFILES=$BUILD_PROFILES" >> "$GITHUB_OUTPUT"

  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - x86_64-pc-windows-gnu
        profile: ${{ fromJson(needs.prepare.outputs.build_profiles) }}
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          allow-unsafe-pr-checkout: true

      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.24.0

      - name: Install cross
        run: cargo binstall --force -y cross

      - name: Build redlib
        run: |
          # cargo clean is because https://github.com/cross-rs/cross/issues/724
          cargo clean
          if [ "${{ matrix.profile }}" = "release" ]; then
            cross build --release --target ${{ matrix.target }}
          elif [ "${{ matrix.profile }}" = "debug" ]; then
            cross build --target ${{ matrix.target }}
          else
            echo "Unknown build profile! ${{ matrix.profile }}"
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: redlib-${{ matrix.profile }}-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/redlib
            target/${{ matrix.target }}/release/redlib.exe
            target/${{ matrix.target }}/debug/redlib
            target/${{ matrix.target }}/debug/redlib.exe
          compression-level: 9
          if-no-files-found: error
