name: Build Redlib

on:
  push:
    paths-ignore:
      - "*.md"
      - "compose.*"
    branches:
      - "main"
  workflow_dispatch:

env: 
  CARGO_TERM_COLOR: always

  CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"
  CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"

permissions:
  contents: read

jobs:
  build:
    name: Build Redlib
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}

      - name: Install cross
        run: |
          cargo install cargo-binstall
          cargo binstall cross --force -y

      - name: Extract redlib current version
        id: version
        run: echo "VERSION=$(cargo metadata --format-version 1 --no-deps | jq .packages[0].version -r | sed 's/^/v/')" >> "$GITHUB_OUTPUT"

      - name: Build redlib
        run: |
          # cargo clean is because https://github.com/cross-rs/cross/issues/724
          cargo clean
          cross build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: redlib-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/redlib
            target/${{ matrix.target }}/release/redlib.exe
          compression-level: 9
          if-no-files-found: error
