name: Build Artifact

on:
  push:
    paths-ignore:
      - "*.md"
      - "compose.*"
    branches:
      - "main"
  workflow_dispatch:
  workflow_call:

env: 
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always

  CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"
  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"
  CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_RUSTFLAGS: "-C target-feature=+crt-static -C link-self-contained=yes"

permissions:
  contents: read

jobs:
  build:
    name: Build Artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - x86_64-pc-windows-gnu
        profile:
          - release
          - debug
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          allow-unsafe-pr-checkout: true

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cross
        run: |
          cargo install cargo-binstall
          cargo binstall cross --force -y

      - name: Build redlib
        run: |
          # cargo clean is because https://github.com/cross-rs/cross/issues/724
          cargo clean
          if [ "${{ matrix.profile }}" = "release" ]; then
            cross build --release --target ${{ matrix.target }}
          elif [ "${{ matrix.profile }}" = "debug" ]; then
            cross build --release ${{ matrix.target }}
          else
            echo "Unknown build profile! ${{ matrix.profile }}"
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: redlib-${{ matrix.profile }}-${{ matrix.target }}
          path: |
            if [ "${{ matrix.profile }}" = "release" ]; then
              target/${{ matrix.target }}/release/redlib
              target/${{ matrix.target }}/release/redlib.exe
            elif [ "${{ matrix.profile }}" = "debug" ]; then
              target/${{ matrix.target }}/debug/redlib
              target/${{ matrix.target }}/debug/redlib.exe
            else
              echo "Unknown build profile! ${{ matrix.profile }}"
              exit 1
            fi
          compression-level: 9
          if-no-files-found: error

  upload-version:
    name: Upload Version
    runs-on: ubuntu-slim
    steps: 
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          allow-unsafe-pr-checkout: true

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Extract redlib current version
        id: version
        run: echo "$(cargo metadata --format-version 1 --no-deps | jq .packages[0].version -r | sed 's/^/v/')" > redlib_version

      - name: Upload to artifact
        uses: actions/upload-artifact@v7
        with:
          name: version
          path: redlib_version
          compression-level: 9
          if-no-files-found: error
