name: Code Test

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always
  NEXTEST_RETRIES: 10

on:
  push:
    branches:
      - 'main'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Code Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          allow-unsafe-pr-checkout: true
      
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Run cargo nextest
        run: cargo nextest run
