name: Create Release

env:
  CARGO_TERM_COLOR: always
  REDLIB_VERSION: unknown

on:
  workflow_dispatch:
    inputs:
      draft-release:
        type: boolean
        description: Create release draft
        default: false
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-artifact:
    name: Build Binary
    uses: ./.github/workflows/build-artifacts.yml
    with:
      skip-debug-build: true

  fetch-version:
    name: Upload Version
    runs-on: ubuntu-slim
    outputs:
      redlib_version: ${{ steps.version.VERSION }}
    steps: 
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install rust with cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Extract redlib current version
        id: version
        run: |
          echo "VERSION=$(cargo metadata --format-version 1 --no-deps | jq .packages[0].version -r | sed 's/^/v/')" >> "$GITHUB_OUTPUT"

  create-release:
    name: Create Release
    runs-on: ubuntu-slim
    permissions:
      contents: write
    needs: 
      - build-artifact
      - fetch-version
    steps:
      - name: Download Version Artifact
        uses: actions/download-artifact@v8
        with: 
          name: redlib_version

      - name: Get and store redlib version
        run: echo "REDLIB_VERSION=$(cat ./redlib_version/version)" >> "$GITHUB_ENV"

      - name: Download Redlib Release Artifacts
        uses: actions/download-artifact@v8
        with: 
          name: redlib-release-*

      - name: Package binaries
        run: |
          cd artifacts
          for dir in redlib-release-*; do
            if [ -d "$dir" ]; then
              echo "Processing $dir..."
              if [[ "$dir" == *"windows"* ]]; then
                # Package Windows target as .zip
                (cd "$dir" && zip -9 -r "../${dir}.zip" .)
              else
                # Package Linux/Unix targets as .tar.gz
                tar -cvf -C "$dir" . | gzip -9 - > "${dir}.tar.gz"
              fi
            fi
          done

      - name: Prepare for upload artifact
        run: 
          echo "${{ needs.fetch-version.outputs.redlib_version }}" > ./release_version
      
      - name: Upload release artifact
        uses: actions/upload-artifact@v7
        with:
          name: release_artifact
          path: |
            ./release_version
            ./redlib-release-*/redlib-release-*.tar.gz
            ./redlib-release-*/redlib-release-*.zip
          compression-level: 9
          if-no-files-found: error

      - name: Generate Release
        uses: softprops/action-gh-release@v3
        if: ${{ inputs.draft-release }}
        with:
          tag_name: ${{ needs.fetch-version.outputs.redlib_version }}
          name: ${{ needs.fetch-version.outputs.redlib_version }} - ${{ github.event.head_commit.message }}
          draft: true
          files: |
            ./redlib-release-*/redlib-release-*.tar.gz
            ./redlib-release-*/redlib-release-*.zip
          body: |
            - ${{ github.event.head_commit.message }} ${{ github.sha }}
          generate_release_notes: true