name: Create Release

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
    inputs:
      draft-release:
        type: boolean
        description: Create release draft
        default: false
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-artifacts.yaml
    with:
      skip-debug-build: true

  get-version:
    uses: ./.github/workflows/parse-version.yml

  make-release:
    name: Create Release
    runs-on: ubuntu-slim
    permissions:
      contents: write
    needs: 
      - build
      - get-version
    steps:
      - name: Download Redlib Release Artifacts
        uses: actions/download-artifact@v8
        with: 
          pattern: redlib-release-*

      - name: Package binaries
        run: |
          for dir in redlib-release-*; do
            if [ -d "$dir" ]; then
              echo "Processing $dir..."
              if [[ "$dir" == *"windows"* ]]; then
                # Package Windows target as .zip
                (cd "$dir" && zip -9 -r "../${dir}.zip" .)
              else
                # Package Linux/Unix targets as .tar.gz
                tar -cvf -C "$dir" . | gzip -9 - > "${dir}.tar.gz"
              fi
            fi
          done

      - name: Prepare for upload artifact
        run: 
          echo "${{ needs.get-version.outputs.redlib_version }}" > ./release_version
      
      - name: Upload release artifact
        uses: actions/upload-artifact@v7
        with:
          name: release_artifact
          path: |
            ./release_version
            ./redlib-release-*/release/redlib-release-*.tar.gz
            ./redlib-release-*/release/redlib-release-*.zip
          compression-level: 9
          if-no-files-found: error

      - name: Generate Release
        uses: softprops/action-gh-release@v3
        if: ${{ inputs.draft-release }}
        with:
          tag_name: ${{ needs.get-version.outputs.redlib_version }}
          name: ${{ needs.get-version.outputs.redlib_version }} - ${{ github.event.head_commit.message }}
          draft: true
          files: |
            ./redlib-release-*/redlib-release-*.tar.gz
            ./redlib-release-*/redlib-release-*.zip
          body: |
            - ${{ github.event.head_commit.message }} ${{ github.sha }}
          generate_release_notes: true
