name: Lint Check

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - 'main'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rustfmt:
    name: cargo fmt --all -- --check
    runs-on: ubuntu-slim
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          allow-unsafe-pr-checkout: true
      
      - name: Install rust with rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      # commended because we are using problem matcher for better ui
      # - name: Run cargo fmt
      #   run: cargo fmt --all -- --check

  clippy:
    name: cargo clippy -- -D warnings
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          allow-unsafe-pr-checkout: true

      - name: Install rust with rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      
      - name: Install dependencis
        run: apt-get install -y --no-install-recommends --no-install-suggests gcc g++ git cmake make perl pkg-config libclang-dev nasm

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  conclusion:
    name: Conclude run
    needs:
      - rustfmt
      - clippy
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - name: Check results
        run: |
          echo "Rustfmt result: ${{ needs.rustfmt.outcome }}"
          echo "CLippy result: ${{ needs.clippy.outcome }}"

          if [[ \
            "${{ needs.test-a.outcome }}" == "failure" ||
            "${{ needs.test-b.outcome }}" == "failure"
          ]]; then
            echo "Failed jobs detected"
            exit 1
          fi
