name: Pull Request

on:
  pull_request:

permissions:
  contents: read

jobs:
  fetch-version:
    name: Fetch Version
    uses: ./.github/workflows/fetch-version.yml
  lint-check:
    name: Lint Check
    uses: ./.github/workflows/lint-check.yml
  test-code:
    name: Code Test
    uses: ./.github/workflows/code-test.yml
  build-artifact:
    name: Build Artifact
    uses: ./.github/workflows/build-artifacts.yaml
