name: Pull Request

env:
  CARGO_TERM_COLOR: always
  NEXTEST_RETRIES: 10

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint-check:
    name: Lint Check
    uses: ./.github/workflows/lint-check.yml
  test-code:
    name: Code Test
    uses: ./.github/workflows/code-test.yml
  build-artifact:
    name: Build Artifact
    uses: ./.github/workflows/build-artifacts.yml
